language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t paddymac83/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true paddymac83/react-test npm test

after_success:
  - docker build -t paddymac83/multi-client ./client
  - docker build -t paddymac83/multi-server ./server
  - docker build -t paddymac83/multi-worker ./worker
  - docker build -t paddymac83/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push paddymac83/multi-client
  - docker push paddymac83/multi-server
  - docker push paddymac83/multi-worker
  - docker push paddymac83/multi-nginx

# note, testing out creating the Dockerhub repos first.

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-657412266789'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
